# Mandatory parameters for shovel setup
shovel:
    rabbit-2:
        port: '5671'
        https_port: '8443'
        virtual-host: volttron
        certificates:
            private_cert: "path to private cert" # For example, /home/volttron/vhome/test_shovel/certificates/private/volttron1.shovelvolttron2.pem
            public_cert: "path to public cert" # For example, /home/volttron/vhome/test_shovel/certificates/shovels/volttron2.volttron1.shovelvolttron2.crt
            remote_ca: "path to CA cert" # For example, /home/volttron/vhome/test_shovel/certificates/shovels/volttron2_ca.crt
        # Configuration to forward pubsub topics
        pubsub:
            # Identity of agent that is publishing the topic
            platform.driver:
                # Topic pattern to be forwarded
        - devices
    # Configuration to make remote RPC calls
    rpc:
      # Remote instance name
      volttron2:
        # List of pair of agent identities (local caller, remote callee)
        - [scheduler, platform.actuator]
