---
# This workflow is meant as a foundational workflow for running integration/unit tests on the
# platform.  For this workflow we are testing the
#
# volttrontesting/testutils directory using pytest.
#
# This workflow also shows the caching mechanisms available for storage
# and retrieval of cache for quicker setup of test environments.

name: Testing dbutils directory
on: [push, pull_request]

jobs:
  build:
    # The strategy allows customization of the build and allows matrixing the version of os and software
    # https://docs.github.com/en/free-pro-team@l.atest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: false
      matrix:
        # Each entry in the os and python-version matrix will be run so for the 3 x 4 there will be 12 jobs run
        os: [ ubuntu-18.04, ubuntu-20.04  ]
        python-version: [ 3.6, 3.7] # , 3.8, 3.9 ]

    runs-on: ${{ matrix.os }}
    env:
        TEST_TYPE: dbutils
    steps:
      # checkout the volttron repository and set current directory to it
      - uses: actions/checkout@v2

      # Attempt to restore the cache from the build-dependency-cache workflow if present then
      # the output value steps.check_files.outputs.files_exists will be set (see the next step for usage)
      - name: Set up Python ${{matrix.os}} ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Run the specified tests and save the results to a unique file that can be archived for later analysis.
      - name: Run pytest on ${{ matrix.python-version }}, ${{ matrix.os }}
        uses: volttron/volttron-build-action@v1
        with:
            python_version: ${{ matrix.python-version }}
            os: ${{ matrix.os }}
            test_path: volttrontesting/platform/${{ env.TEST_TYPE }}
            test_output_suffix: ${{ env.TEST_TYPE }}

#       Archive the results from the pytest to storage.
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pytest-report
          path: output/${{ env.TEST_TYPE }}-${{matrix.os}}-${{ matrix.python-version }}-results.xml
